Name: ConfigTest
Version: 1.0.0
DataDir: ./
NodeList:
    Node1:
        Serial: 123456789
        IP: 10.0.0.1
        Protocol: ftp
    Node2:
        ParentNode: Node1
Tags:
    - This
    - Is
    - Test
    - Config
